#!/usr/bin/env bash

#ddev-generated
## Description: Execute Beads (bd) task tracker in the Beads container
## Usage: bd [command] [options]
## Example: ddev bd ready\nddev bd create "New task" -p 1\nddev bd show bd-abc
## ExecRaw: true

ddev exec -s beads bd "$@"
